version: '3'

services:
  mysqld:
    image: mysql:latest
    container_name: bimaapp1
    restart: always
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql

  bima-app:
    image: bimaapp
    ports:
      - "8080:8080"
    depends_on:
      - mysqld
    environment:
      MYSQL_HOST: mysqld
      

volumes:
  mysql-data: